const cfg=window.ICELL_SUPABASE||{};
const configured=cfg.url&&!cfg.url.includes('SEU-PROJETO')&&cfg.anonKey&&!cfg.anonKey.includes('SUA-ANON');
const sb=configured?supabase.createClient(cfg.url,cfg.anonKey):null;
const $=s=>document.querySelector(s); let all=[];
function toast(msg,type='ok'){const t=$('#toast');t.textContent=msg;t.className=`toast ${type} show`;setTimeout(()=>t.classList.remove('show'),2600)}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function checkSession(){if(!sb){toast('Configure o Supabase em supabase-config.js','err');return}const {data:{session}}=await sb.auth.getSession();if(session)showAdmin();}
async function showAdmin(){ $('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');await load();lucide.createIcons() }
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!sb)return toast('Configure o Supabase primeiro.','err');const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)return toast('Login inválido ou sem acesso.','err');showAdmin()});
$('#logoutBtn').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
async function load(){const {data,error}=await sb.from('products').select('*').order('created_at',{ascending:false});if(error)return toast(error.message,'err');all=data||[];renderRows();stats()}
function stats(){ $('#statPublished').textContent=all.filter(p=>p.status==='published').length;$('#statStock').textContent=all.reduce((a,p)=>a+Number(p.stock||0),0);$('#statFeatured').textContent=all.filter(p=>p.featured).length }
function renderRows(){const q=$('#adminSearch').value.toLowerCase();const rows=all.filter(p=>[p.name,p.model,p.storage,p.color].join(' ').toLowerCase().includes(q));$('#adminEmpty').classList.toggle('hidden',rows.length>0);$('#productRows').innerHTML=rows.map(p=>`<tr><td><div class="product-cell">${p.image_url?`<img class="thumb" src="${esc(p.image_url)}">`:'<div class="thumb"></div>'}<div><b>${esc(p.name)}</b><span>${esc(p.storage||'')} • ${esc(p.color||'')}</span></div></div></td><td>${esc(p.condition||'')}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><span class="pill ${p.status==='published'?'published':''}">${p.status==='published'?'Publicado':'Rascunho'}</span></td><td><button class="edit-btn" data-id="${p.id}"><i data-lucide="pencil"></i></button></td></tr>`).join('');document.querySelectorAll('.edit-btn').forEach(b=>b.onclick=()=>openModal(all.find(p=>p.id===b.dataset.id)));lucide.createIcons()}
$('#adminSearch').addEventListener('input',renderRows);
function openModal(p=null){$('#productModal').classList.remove('hidden');$('#modalTitle').textContent=p?'Editar aparelho':'Novo aparelho';$('#deleteBtn').classList.toggle('hidden',!p);$('#productForm').reset();$('#productId').value=p?.id||'';$('#name').value=p?.name||'';$('#model').value=p?.model||'';$('#storage').value=p?.storage||'';$('#color').value=p?.color||'';$('#condition').value=p?.condition||'Novo';$('#price').value=p?.price??'';$('#oldPrice').value=p?.old_price??'';$('#installments').value=p?.installments??12;$('#battery').value=p?.battery_health??'';$('#stock').value=p?.stock??1;$('#status').value=p?.status||'published';$('#imageUrl').value=p?.image_url||'';$('#featured').checked=!!p?.featured;lucide.createIcons()}
function closeModal(){$('#productModal').classList.add('hidden')}
$('#newProductBtn').onclick=()=>openModal();$('#closeModal').onclick=closeModal;$('#cancelBtn').onclick=closeModal;$('#productModal').addEventListener('click',e=>{if(e.target.id==='productModal')closeModal()});
async function upload(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('products').upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;return sb.storage.from('products').getPublicUrl(path).data.publicUrl}
$('#productForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#saveBtn');btn.disabled=true;btn.textContent='Salvando...';try{let image_url=$('#imageUrl').value.trim()||null;const file=$('#imageFile').files[0];if(file)image_url=await upload(file);const payload={name:$('#name').value.trim(),model:$('#model').value.trim(),storage:$('#storage').value.trim(),color:$('#color').value.trim(),condition:$('#condition').value,price:Number($('#price').value),old_price:$('#oldPrice').value?Number($('#oldPrice').value):null,installments:$('#installments').value?Number($('#installments').value):null,battery_health:$('#battery').value?Number($('#battery').value):null,stock:Number($('#stock').value),status:$('#status').value,image_url,featured:$('#featured').checked};const id=$('#productId').value;const res=id?await sb.from('products').update(payload).eq('id',id):await sb.from('products').insert(payload);if(res.error)throw res.error;toast(id?'Aparelho atualizado.':'Aparelho adicionado.');closeModal();await load()}catch(err){toast(err.message||'Erro ao salvar.','err')}finally{btn.disabled=false;btn.textContent='Salvar aparelho'}});
$('#deleteBtn').addEventListener('click',async()=>{const id=$('#productId').value;if(!id||!confirm('Excluir este aparelho do catálogo?'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error)return toast(error.message,'err');toast('Aparelho excluído.');closeModal();load()});
lucide.createIcons();checkSession();
